In [114]:
import numpy as np 
class LinearRegression():
    """
    x : input vector , 2-d numpy array 
    y : labels for each input vector , 1-d numpy array 
    alpha : learning rate 
    lambda : regularization rate 
    epochs : number of training epochs 
    degree : polynomial degree of the hypothesis function 
    
    """
    def __init__(self,x,y,alpha=0.0001,lambda_=0.001,epochs=100):
        self.x = np.array(x) 
        new_col = np.full((self.x.shape[0],1),1)
        print(new_col)
        self.x = np.hstack((new_col,self.x))
        print(self.x)
        self.y = np.array(y)
        self.alpha = alpha
        self.lambda_ = lambda_
        self.epochs = epochs 
        self.thetas = np.full((1,self.x.shape[1]),0.5)
        print(self.thetas)
        
    def fit(self):
        for epoch  in range(self.epochs):
            
            grads = np.zeros(self.thetas.shape[1])
            
            for i,input_x in enumerate(self.x):
                pred = np.dot(self.thetas,input_x.T)
                actual = self.y[i]
                error = pred - actual
                
                for i in range(self.thetas.shape[1]):
                    grads[i] += (error*(input_x[i].item()) + self.lambda_*(self.thetas[0,i].item()))
            grads = grads * (1/self.x.shape[0])
            self.thetas = self.thetas - (self.alpha * grads) 
        print(self.thetas)
    
    def predict(self,x):
        x = np.array(x)
        return np.dot(self.thetas,x.T)
                
                

In [115]:
# actual data testing 

model = LinearRegression(x=[[73,67,43],
        [91,88,64],
        [87,134,58],
        [102,43,37],
        [69,96,70]], y = [56,81,119,22,103],epochs=1000)
model.fit()
model.predict(x=[1,70,34,45])

[[1]
 [1]
 [1]
 [1]
 [1]]
[[  1  73  67  43]
 [  1  91  88  64]
 [  1  87 134  58]
 [  1 102  43  37]
 [  1  69  96  70]]
[[0.5 0.5 0.5 0.5]]
[[ 0.49237692 -0.40399652  0.84812251  0.68424784]]


/tmp/ipykernel_1162/3828959946.py:36: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  grads[i] += (error*(input_x[i].item()) + self.lambda_*(self.thetas[0,i].item()))


array([31.83993877])

In [116]:
model = LinearRegression(x=[[1,1],[2,2]],y=[1,2],epochs=1000)
model.fit() 
model.predict([1,1,1])

[[1]
 [1]]
[[1 1 1]
 [1 2 2]]
[[0.5 0.5 0.5]]
[[0.46135154 0.4436017  0.4436017 ]]


/tmp/ipykernel_1162/3828959946.py:36: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  grads[i] += (error*(input_x[i].item()) + self.lambda_*(self.thetas[0,i].item()))


array([1.34855494])